In [2]:
import torch

In [3]:
# Initialize tensor with gradient tracking
x = torch.ones(2,2,requires_grad=True)
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [5]:
# Do a tensor operation
y = x + 2
print(y)
print(y.grad_fn)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


In [6]:
z = y * y * 3
out = z.mean()
print(z,out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward1>)


In [9]:
# Toggle grad function
a = torch.randn(2,2)
a = ((a * 3) / (a - 1))
print(a.requires_grad)
a.requires_grad_(True)
print(a.requires_grad)
b = (a * a).sum()
print(b)
print(b.grad_fn)

False
True
tensor(39.1049, grad_fn=<SumBackward0>)


In [11]:
# d(out)/dx
# The value out is 27, and was defined above
# in two steps as a function of x.
print(x.grad)

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


In [12]:
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


Jacobian vector product
-----------------------------

In [15]:
x  = torch.randn(3,requires_grad=True)
y = x * 2

while y.data.norm() < 1000:
  y = y * 2
    
print(y)

tensor([-421.8176, 1295.9218, 1025.2225], grad_fn=<MulBackward0>)


In [19]:
v = torch.tensor([0.1,1.0,0.0001],dtype=torch.float)
y.backward(v)

print(x.grad)

RuntimeError: Trying to backward through the graph a second time, but the buffers have already been freed. Specify retain_graph=True when calling backward the first time.

Wrap with no grad
----------------------

In [18]:
print(x.requires_grad)
print((x ** 2).requires_grad)

with torch.no_grad():
    print((x ** 2).requires_grad)

True
True
False
