In [3]:
from __future__ import print_function
import torch 

In [10]:
# Uninitialized tensor with 5 rows and 3 columns
x = torch.empty(5, 3)
print(x)

tensor([[0.0000e+00, 2.0000e+00, 1.3198e+04],
        [2.5250e-29, 4.7339e+30, 2.9514e+29],
        [1.4607e-19, 1.8888e+31, 3.1035e+27],
        [3.3460e-12, 1.4583e-19, 1.8888e+31],
        [4.9656e+28, 7.9463e+08, 5.0944e-14]])


In [9]:
# Tensor initialized with 0
x = torch.zeros(5,3)
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [8]:
# Tensor with random values
x = torch.rand(5,3)
print(x)

tensor([[0.2778, 0.4030, 0.4924],
        [0.9908, 0.7856, 0.2035],
        [0.1593, 0.1547, 0.2906],
        [0.1876, 0.1282, 0.6088],
        [0.5053, 0.5611, 0.8329]])


In [12]:
# Ones and dtype long
x = torch.ones(5,3, dtype=torch.long)
print(x)

tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]])


In [21]:
# Construct a tensor from python data
y = torch.tensor([[1.1, 1.2],[2.1,2.2],[3.1,3.2]])
print(y)
print(y.size())

tensor([[1.1000, 1.2000],
        [2.1000, 2.2000],
        [3.1000, 3.2000]])
torch.Size([3, 2])


In [29]:
# Create based on an existing one. 
z = x.new_zeros(6,3,dtype=torch.float)
print(z)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


Operations
-------------

In [31]:
# Sum
x = torch.ones(3,3)
y = x + x
print(y)
# Other syntax
print(torch.add(x,y))

tensor([[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]])
tensor([[3., 3., 3.],
        [3., 3., 3.],
        [3., 3., 3.]])


In [33]:
# Provide an output location for the sum
r = torch.empty(3,3)
torch.add(y,y,out=r)
print(r)

tensor([[4., 4., 4.],
        [4., 4., 4.],
        [4., 4., 4.]])


In [36]:
# In place addition
r.add_(y)
print(r)

tensor([[6., 6., 6.],
        [6., 6., 6.],
        [6., 6., 6.]])


In [39]:
# Wildcard indexing
print(r[:,1])

tensor([6., 6., 6.])


NumPy bridge
-----------------

In [40]:
# Conversion from torch to numpy
a1 = torch.ones(5)
print(a1)
a2 = a1.numpy()
print(a2)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]


In [42]:
# Array data is shared across torch and numpy
a1.add_(1)
print(a1)
print(a2)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [44]:
# Conversion from numpy to torch
import numpy as np
b1 = np.ones(5)
b2 = torch.from_numpy(b1)
np.add(b1,1,out=b1)
print(b1)
print(b2)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
